version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - cd frontend/webpage # Navigate to the directory containing your package.json
        - npm install
    build:
      commands:
        - npm run build # Replace with your build command
  artifacts:
    # Files to include in the deployment
    baseDirectory: /path/to/build/directory
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
